variable "AWS_ACCESS_KEY" {}
variable "AWS_SECRET_KEY" {}
variable "AWS_DEFAULT_REGION" {}
variable "aws_key_name" {}
variable "aws_key_path" {}
variable "aws_region" {}
variable "yutani_home" {}
variable "nginx_lb" {}
variable "consul_server" {}
variable "aws_delegation_id" {}
variable "chef_server_url" {}
variable "bastion_ip" {}
variable "chef_user_key" {}
variable "chef_username" {}
variable "tfstate_key" {}
variable "tfstate_bucket" {}
variable "tfstate_region" {}
